services:
  frontend:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./dashboard:/app
    depends_on:
      - backend

  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5500:5500'
    volumes:
      - ./api:/app